config/routes.rb
Rails.application.routes.draw do
  root 'landing#front'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'afterlogin' =>  'landing#afterlogin'
  delete 'logout'  => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'newhabit' => 'habits#new'
  get 'all' => 'users#all'
  
  resources :habits
  resources :tracks, controller: "tracker" 
  post 'tracker/increase_streak' => 'tracker/increase_streak'
  post 'tracker/reset_streak' => 'tracker/reset_streak'
  post 'tracker/reset_counter' => 'tracker/reset_counter'
  resources :users
  
end

app/models/habit.rb
class Habit < ActiveRecord::Base
    belongs_to :user
    has_one :track, dependent: :destroy
    validate :habits_count
    validates :habit_title,  presence: true

    private
    
    def habits_count
        return unless self.user.habits.size > 2
        if self.user.habits.size > 2
          errors.add(:base, "Let's only work on 2 habits at a time")
          return false
        end
    end
end

app/models/track.rb
class Track < ActiveRecord::Base
    belongs_to :habit
    before_save :default_values
    
    def default_values
         self.streak ||= '0'
         self.compday ||= '0'
         self.skipdays ||= '0'
         self.checker ||= '0'
    end
end

app/models/update.rb
class Update < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :habits, dependent: :destroy
  has_many :tracks, :through => :habits
  validates_associated :habits
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
                      
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:  {case_sensitive: false} 
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
 
   # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:show, :edit, :update, :destroy]

  # GET /habits
  # GET /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
    #@habits = Habit.find(habit_params)
    @habit = Habit.find(params[:id])
  end

  # GET /habits/new
  def new
    @habit = Habit.new
    # @track = @order = @customer.orders.create(order_date: Time.now)
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits
  # POST /habits.json
  def create
      @user = User.find_by(id: session[:user_id])
      @habit = @user.habits.new(habit_params)
      @track = @habit.create_track(streak: 0, longdate: Time.now, newstart: Time.now)
      respond_to do |format|
        if @habit.save
          format.html { redirect_to root_url, notice: 'Habit was successfully created.' }
        else
          format.html { render :new }
        end
      end
    
  end

  # PATCH/PUT /habits/1
  # PATCH/PUT /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to root_url, notice: 'Habit was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Habit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def habit_params
       params.require(:habit).permit(:habit_category, :habit_title, :habit_description, :habit_duration)
    end
    
    def track_params
      params.require(:track).permit(:name, :date, :streak, :habit_done)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
    
    def front
        if logged_in?
            @user = User.find(current_user.id)
            @habits = Habit.all
            @tracks = Track.all
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tracker_controller.rb
class TrackerController < ApplicationController

    def index
       @tracks = Track.all
    end
    
    def new
        @track = Track.new
    end
    
    def show
        @track = Track.find(params[:id])
        
    end
    
    def progress
        @track = Track.find(params[:id])
    end
        
    def edit
    end
    
    def create
        @track = Track.new(track_params)
    end
    
    def update
    end

    def increase_streak
        track = Track.find(params[:track_id])
        # to get a new starting date
        track.newstart = Time.now unless track.streak != 0
        if track.checker< 1
            track.increment(:streak, 1) unless track.streak > 20 
            #to keep track of longest streak
            track.compday = track.streak unless track.streak <= track.compday
            track.checker += 1
            if track.save
                notification = 'Successfully Updated'
                
            else
                notification = 'Failed to update' 
            end
            
        end
        redirect_to track_path(track), notice: notification
        
    end
    
    def reset_streak
        track = Track.find(params[:track_id])
        # to get last date of the streak
        track.longdate = Time.now
        if track.checker< 1    
            track.streak = 0
            track.increment(:skipdays, 1) 
            track.checker += 1
            if track.save
                notification = 'Successfully Updated'
            else
                notification = 'Failed to update' 
            end
        end
        redirect_to track_path(track), notice: notification
    end
    
    def reset_counter
       track =  Track.find(params[:track_id])
       track.checker = 0
       track.save
       redirect_to track_path(track)
    end
    
    def historypage
        @habits = Habit.all
        @tracks = Track.all
    end
    
    private
    
    def track_params
        params.require(:track).permit( :name, :streak, :habit_done)
    end
    
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
    
    def answer
       update.answer = true 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def all
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the habit_builder!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tracker_helper.rb
module TrackerHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/habits/_form.html.erb
<%= render 'habits/error_message', object: f.object %>

<%= f.label :habit_category, "Category" %>
<% collection = [   ['LifeStyle / Enrichment', 'LifeStyle / Enrichment'], 
                    ['Quit Bad Habit', 'Quit Bad Habit'],
                    ['Keep Fit and Healthy', 'Keep Fit and Healthy']
                ]%>
<%= f.select :habit_category, collection %>
<br><br><br>

<%= f.label :habit_title, "Here's some suggestions for your habit title"%>
<br>
<% collectionT = [   [' ', ' '],
                     ['Exercise', 'Exercise'],
                     ['Have Breakfast', 'Have Breakfast'],
                     ['Meditation', 'Meditation'],
                     ['Read Favourite Book', 'Read Favourite Book'],
                     ['8 Glasses of Water a day', '8 Glasses of Water a day'],
                     ['An apple a day', 'An apple a day'],
                     ['Wake up early', 'Wake up early'],
                     ['Write a to-do-list', 'Write a to-do-list'],
                     ['Check News of the day', 'Check News of the day'],
                     ['Smile to stranger', 'Smile to stranger'],
                     ['No Smoking', 'No Smoking'],
                     ['No Snack', 'No Snack'],
                     ['No Fast Food', 'No Fast Food'],
                     ['No Alcohol', 'No Alcohol'],
                     ['No Coffee', 'No Coffee'],
                     ['No Social Media', 'No Social Media'],
                     ['Others', 'Others']
                ]%>
<%= f.select :habit_title, collectionT %>
<br><br><br>
<%= f.label :habit_title, "Title" %>
<%= f.text_field :habit_title, class: 'form-control'%>


<br><br>

<%= f.label :habit_description, "Description" %>
<%= f.text_field :habit_description, class: 'form-control' %>

<br><br>

<%= f.label :habit_duration, "Duration" %>
<% collectionD = [    ['21','21']   ]%>
<%= f.select :habit_duration, collectionD %>
<br><br>

app/views/habits/edit.html.erb
<% provide(:title, 'Edit Habit') %>

<div class="container-fluid">
<div class="row header-form">
  <div class="col-md-4 col-md-offset-4">
    <h2>Edit Habit</h2>
  </div>
</div>  
</div>


<div class="row body-form">
    <div class="col-md-6 col-md-offset-3 " >
        <%= form_for(@habit) do |f| %>
            <%= render 'habits/form', f: f %>
            <br></br>
            <%= f.submit "Ready to go !", class: "btn btn-success" %>
            <%= link_to 'Back', root_url, class:"btn btn-warning"  %>
        <% end %>
        
   </div>  
</div>

app/views/habits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Habits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= habit.habit_title %></td>
        <td><%= link_to 'Show', track_path(habit.id) %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Habit', new_habit_path %>

app/views/habits/new.html.erb
<% provide(:title, 'New Habit') %>

<div class="container-fluid">
<div class="row header-form">
  <div class="col-md-4 col-md-offset-4">
    <h2>New Habit</h2>
  </div>
</div>  
</div>


<div class="row body-form">
    <div class="col-md-6 col-md-offset-3 " >
        <%= form_for(@habit) do |f| %>
        
            <%= render 'habits/form', f: f %>
            <br></br>
            <%= f.submit "Start work on my habit", class: "btn btn-success" %>
            <%= link_to 'Back', root_url, class:"btn btn-warning"  %>
        <% end %>
        
        
        
   </div>  
</div>

app/views/habits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category :   </strong>
  <%= @habit.habit_category %>
</p>

<p>
  <strong>Title :   </strong>
  <%= @habit.habit_title %>
</p>

<p>
  <strong>Description :   </strong>
  <%= @habit.habit_description %>
</p>

<p>
  <strong>Duration :   </strong>
  <%= @habit.habit_duration %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', root_url %>

app/views/layouts/_header.html.erb
<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "templatemo_flicker", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>
    <header>
    <!-- start menu -->
    <div id="templatemo_home">
    	<div class="templatemo_top">
      <div class="container templatemo_container">
        <div class="row">
          <div class="col-sm-3 col-md-3">
            <div class="logo">
              <a href=""><img src= <%= asset_path "images/templatemo_logo.png" %> alt="smoothy html5 template"></a>
            </div>
          </div>
          <div class="col-sm-9 col-md-9 templatemo_col9">
          	<div id="top-menu">
            <nav class="mainMenu">
              <ul class="nav">

                <% if logged_in? %>
                <li><a class="menu" href="/">Home</a></li>
                <!--<li><a class="menu" href="/">Progress</a></li>-->
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                
                <% elsif %>
                <li><a class="menu" href="/">Home</a></li>
                <li><a class="menu" href="/#templatemo_portfolio">How</a></li>
                <li><a class="menu" href="/#templatemo_blog">Feedback</a></li>
                <li><a class="menu" href="/#templatemo_partners">Meet Our Team</a></li>
                <li><%= link_to "Sign up", signup_path %></li>
                <li><%= link_to "Login", login_path %></li>
                <% end %>
              </ul>
            </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="clear"></div>
    <!-- end menu -->

  </header>

app/views/layouts/_shim.html.erb
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Habit Builder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
    <meta name="keywords" content="" />
  	<meta name="description" content="" />

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/templatemo_style.css" rel="stylesheet">
   	<link rel="stylesheet" href="css/templatemo_misc.css">

    <link href="css/circle.css" rel="stylesheet">
    <link href="css/jquery.bxslider.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/nivo-slider.css">
    <link rel="stylesheet" href="css/slimbox2.css" type="text/css" media="screen" /> 
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,600' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/JavaScript" src="js/slimbox2.js"></script> 
	
    <link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css" />
  	<script type="text/javascript" src="js/jquery.min.js"></script>
  	<script type="text/javascript" src="js/ddsmoothmenu.js"></script>
  
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tracker/historypage.html.erb
<h1>Listing Habits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td> <%= habit.habit_title %> </td>
        <td> Longest streak is <%= habit.track.streak %> </td>
        <td> Habit completed at  </td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tracker/home.html.erb
<h1>Start Tracking</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@track) do |f| %>
            <%= f.label :Title %>

            <br></br>
            <label for "title">Habit stats</label>
            <br></br>
            <%= f.text_field :date, class: 'form-control' %>
            <br></br>
            <%= f.label :streak %>
            <br></br>
            <%= f.text_field :habit_done, class: 'form-control' %>
            
            <%= f.submit "Begin my habit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/tracker/index.html.erb
<div class="page-header">
  <h1>Index page</h1>
</div>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <div class="row ">
    <aside class="col-md-4">
        <p>The Habit Starts Today</p>
        <p>The Habit is at</p>
        <h1><%= track.streak %> days</h1>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
            <%= track.streak %> days
          </div>
        </div>
        <p>Completion of the Habit</p>
    </aside>
</div>
    <% end %>
  </tbody>
</table>

app/views/tracker/show.html.erb
<% provide(:title, 'Progress') %>

<div class="container-fluid">
<div class="row header-form">
  <div class="col-md-4 col-md-offset-4">
  <h2>Progress of habit</h2>

  </div>
</div>  
</div>

<div class="row body-form">
    <div class="col-md-6 col-md-offset-3 " >
      	<div class="panel panel-warning">
      	  
    		  <div class="panel-heading">
    		    <h3 class="panel-title ">Status</h3>
    		  </div>
    		  
    		  <div class="panel-body">
             <% if @track.streak >= 21 %>
                <h1>!!!!!!!!!!Congratulations You have Built Your Habit!!!!!!!!!</h1>
                <h2>Completed on <%= Time.now.strftime("%m/%d/%Y") %></h2>
                
            <% else %>
              
              <h2 style= "text-align:center">Have you done your habit Today? </h2>
              
              <div style= "text-align:center">  
                <%= link_to 'YES', tracker_increase_streak_path(track_id: @track.id), method: :post , class: "btn btn-lg btn-success" %> 
                <%= link_to 'NO', tracker_reset_streak_path(track_id: @track.id), method: :post, class: "btn btn-lg btn-danger" %>
              </div>  
              
            <% end %>
      		</div>
    		</div> <!-- end panel-->
     
            
        <ul class="list-group">
            <li class="list-group-item">The Habit created on <strong><%= @track.created_at.strftime("%b %d, %Y") %></strong></li>
            <li class="list-group-item">The Habit is already practised for <strong><%= @track.streak %> days</strong></li>
            <li class="list-group-item">Starting from <strong> <%= @track.newstart %></strong>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= (@track.streak.to_f/ 21 * 100).round %>%;">
                  <%= @track.streak %> days
                </div>
            </div>
            </li>
            <li class="list-group-item">The Longest streak is <strong><%= @track.compday %></strong> days from <strong><%= @track.newstart %> to <%= @track.longdate %></strong></li>
            <li class="list-group-item">You have skip your habit for <strong><%= @track.skipdays %> </strong>days</li>
      </ul>
              

      <%= link_to 'Back', root_url, class:"btn btn-warning"  %>
    
   </div>  
</div>

app/views/users/all.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <% @users.each do |user| %>
          <tr>
              <strong>Name: </strong>
              <td><%= user.name %></td>
              <br>
              <strong>Email: </strong>
              <td><%= user.email %></td>
              <br>
              <br>
          </tr>
        <% end %>
        <br>
        <%= link_to "Home", root_url%>
      </h1>
    </section>
  </aside>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container-fluid">
<div class="row header-form">
  <div class="col-md-4 col-md-offset-4">
    <h2>Sign up</h2>
  </div>
</div>  
</div>

<div class="row body-form">
  <div class="col-md-6 col-md-offset-3 " >
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <br>
      <%= f.label :password_confirmation, "Confirmation Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
  
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary btn-success" %>
      <%= button_tag 'Reset', :type => 'reset',class: "btn btn-danger" %>
      <h5>Already have an account? <%= link_to "Login here!", login_path %></h5>
  
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6">User Info
      <br>
      <%= @user.name %>
      <br>
      <%= @user.email %>
  </div>
  
  <div class="col-md-4 col-sm-5 col-xs-6">
    <%= link_to "Add habit", newhabit_path %>
  </div>
</div>